services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: dica-br-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
    command: npx expo start --tunnel