import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  backHeader: {
    position: "relative",
    marginHorizontal: -24,
    marginTop: 11,
    marginBottom: 20,
    paddingHorizontal: 24,
    paddingTop: 14,
    paddingBottom: 20,
    minHeight: 90,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  logoHeader: {
    position: "relative",
    marginHorizontal: -24,
    marginBottom: 18,
    paddingHorizontal: 24,
    paddingTop: 14,
    paddingBottom: 20,
    minHeight: 82,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerShadow: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 1,
    backgroundColor: "rgba(0,0,0,0.06)",
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 4,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  headerRightWrap: {
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  headerRightText: {
    color: "#01AB51",
    fontSize: 22,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: "Poppins-Bold",
  },
  logoWrap: {
    flexDirection: "row",
    alignItems: "center",
  },
  logoImage: {
    width: 126,
    height: 42,
  },
  logoTitleWrap: {
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  logoTitleText: {
    color: "#01AB51",
    fontSize: 22,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: "Poppins-Bold",
  },
});