import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  camera: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
  },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    minHeight: 120,
    paddingHorizontal: 28,
    paddingTop: 74,
    backgroundColor: "transparent",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  backButton: {
    width: 44,
    height: 44,
  },
  titleWrap: {
    flex: 0,
    marginLeft: 12,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  title: {
    color: "#FFFFFF",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
  },
  topActions: {
    position: "absolute",
    top: 137,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  actionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(120,120,128,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  frameWrap: {
    position: "absolute",
    left: "50%",
    top: "50%",
    width: 301,
    height: 270,
    marginLeft: -150.5,
    marginTop: -135,
  },
  frameCornerTopLeft: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 56,
    height: 56,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderColor: "rgba(255,255,255,0.8)",
    borderTopLeftRadius: 18,
  },
  frameCornerTopRight: {
    position: "absolute",
    right: 0,
    top: 0,
    width: 56,
    height: 56,
    borderTopWidth: 2,
    borderRightWidth: 2,
    borderColor: "rgba(255,255,255,0.8)",
    borderTopRightRadius: 18,
  },
  frameCornerBottomLeft: {
    position: "absolute",
    left: 0,
    bottom: 0,
    width: 56,
    height: 56,
    borderBottomWidth: 2,
    borderLeftWidth: 2,
    borderColor: "rgba(255,255,255,0.8)",
    borderBottomLeftRadius: 18,
  },
  frameCornerBottomRight: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 56,
    height: 56,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderColor: "rgba(255,255,255,0.8)",
    borderBottomRightRadius: 18,
  },
  bottomActions: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 78,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 18,
    marginLeft: -55,
  },
  galleryButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  captureButton: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "rgba(0,0,0,0.02)",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.95)",
    alignItems: "center",
    justifyContent: "center",
  },
  captureButtonInner: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(46,46,46,0.75)",
  },
  loadingWrap: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.55)",
  },
  loadingCard: {
    paddingHorizontal: 22,
    paddingVertical: 18,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.92)",
  },
  loadingText: {
    color: "#085491",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
  },
  permissionWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    backgroundColor: "#000000",
    gap: 18,
  },
  permissionTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    textAlign: "center",
  },
  permissionText: {
    color: "#D7D7D7",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "500",
    textAlign: "center",
  },
  permissionButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "#01AB51",
  },
  permissionButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
});
