import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 120,
    backgroundColor: "#FFFFFF",
    paddingTop: 52,
    paddingHorizontal: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 26,
    elevation: 6,
    zIndex: 20,
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  backButtonIcon: {
    color: "#01AB51",
    fontSize: 28,
    lineHeight: 28,
    fontWeight: "500",
  },
  headerTitle: {
    color: "#01AB51",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: "Poppins-Bold",
    flex: 1,
    textAlign: "right",
    marginLeft: 12,
  },
  content: {
    flex: 1,
    position: "relative",
  },
  sectionTitle: {
    position: "absolute",
    color: "#1F1F1F",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    fontFamily: "Poppins-Bold",
  },
  tray: {
    position: "absolute",
    backgroundColor: "#DADADA",
    borderRadius: 62,
    overflow: "hidden",
    alignItems: "center",
    zIndex: 20,
    elevation: 20,
  },
  trayList: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    paddingHorizontal: 18,
  },
  traySlot: {
    width: 72,
    height: 72,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(31,31,31,0.08)",
    backgroundColor: "rgba(255,255,255,0.24)",
  },
  helperText: {
    position: "absolute",
    color: "#1F1F1F",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "400",
    fontFamily: "Poppins-Regular",
  },
  foodCard: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "flex-start",
    zIndex: 50,
    elevation: 50,
  },
  foodCardTray: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 0,
    overflow: "visible",
    flexShrink: 0,
  },
  foodTokenWrap: {
    position: "relative",
    width: 54,
    height: 66,
    alignItems: "center",
    justifyContent: "flex-start",
    overflow: "visible",
  },
  foodLabelArcWrap: {
    position: "absolute",
    top: 0,
    width: 82,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  foodLabelArcLetter: {
    position: "absolute",
    color: "#1F1F1F",
    fontSize: 9,
    lineHeight: 7,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
    textAlign: "center",
    width: 8,
    height: 8,
  },
  foodLabelArcFallback: {
    position: "absolute",
    top: -1,
    color: "#1F1F1F",
    fontSize: 9,
    lineHeight: 9,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
    textAlign: "center",
    width: 76,
    opacity: 0.92,
  },
  foodTile: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginTop: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(31,31,31,0.14)",
    paddingHorizontal: 4,
  },
  foodLabel: {
    color: "rgba(255,255,255,0)",
    fontSize: 8,
    lineHeight: 9,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
    textAlign: "center",
    width: 38,
  },
  boardWrapper: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
    elevation: 1,
  },
  boardBackground: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "100%",
    height: "100%",
  },
  plateLayer: {
    position: "absolute",
  },
  zoneClip: {
    position: "absolute",
    overflow: "hidden",
  },
  plateImage: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "100%",
    height: "100%",
  },
  zoneImage: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "100%",
    height: "100%",
  },
  zoneGreen: {
  },
  zoneYellow: {
    transform: [{ scaleX: -1 }, { rotate: "-90deg" }],
  },
  zoneBlue: {
    transform: [{ scaleX: -1 }, { rotate: "90deg" }],
  },
  zoneMirror: {
    transform: [{ scaleX: -1 }],
  },
  finishButton: {
    position: "absolute",
    width: 228,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    shadowColor: "#196926",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 0,
    elevation: 5,
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
  },
  finishButtonDisabled: {
    opacity: 0.7,
  },
  finishButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
});