import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 120,
    backgroundColor: "#FFFFFF",
    paddingTop: 52,
    paddingHorizontal: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 26,
    elevation: 6,
    zIndex: 10,
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  backButtonIcon: {
    color: "#01AB51",
    fontSize: 28,
    lineHeight: 28,
    fontWeight: "500",
  },
  headerTitle: {
    color: "#01AB51",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: "Poppins-Bold",
    flex: 1,
    textAlign: "right",
    marginLeft: 12,
  },
  scrollContent: {
    flex: 1,
    paddingHorizontal: 32,
    paddingTop: 16,
    paddingBottom: 30,
    justifyContent: "space-between",
  },
  copyBlock: {
    gap: 6,
  },
  title: {
    color: "#1F1F1F",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  paragraph: {
    color: "#1F1F1F",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "400",
    fontFamily: "Poppins-Regular",
  },
  howToBlock: {
    marginTop: 22,
    gap: 6,
  },
  howToTitle: {
    color: "#1F1F1F",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
  },
  howToText: {
    color: "#1F1F1F",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "400",
    fontFamily: "Poppins-Regular",
  },
  imageWrap: {
    alignItems: "center",
    marginTop: 28,
  },
  heroImage: {
    width: 300,
    height: 189,
  },
  primaryButton: {
    alignSelf: "center",
    width: 178,
    height: 44,
    backgroundColor: "#4BB05B",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
    shadowColor: "#196926",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 5,
    marginBottom: 60,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
});