import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  content: {
    flex: 1,
    paddingTop: 48,
    paddingHorizontal: 24,
    paddingBottom: 110,
  },
  sectionTitle: {
    color: "#1C1C1C",
    fontSize: 26,
    lineHeight: 30,
    fontWeight: "800",
    marginBottom: 12,
  },
  profileCard: {
    backgroundColor: "#135E9A",
    borderRadius: 18,
    padding: 18,
    minHeight: 150,
    overflow: "hidden",
    marginBottom: 28,
  },
  profileCardTextWrap: {
    width: "66%",
  },
  profileCardTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "900",
    marginBottom: 8,
  },
  profileCardText: {
    color: "#EAF4FF",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    marginBottom: 14,
  },
  profileButton: {
    alignSelf: "flex-start",
    backgroundColor: "#55C06B",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  profileButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  profileIllustration: {
    position: "absolute",
    right: 10,
    bottom: 8,
    width: 108,
    height: 108,
    borderRadius: 54,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  sectionHeaderTitle: {
    color: "#1C1C1C",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
  },
  sectionHeaderAction: {
    color: "#1C1C1C",
    fontSize: 16,
    fontWeight: "600",
  },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
    paddingTop: 12,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderTopColor: "#E6E6E6",
    overflow: "visible",
  },
  bottomNavRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-around",
    paddingHorizontal: 12,
  },
  navItem: {
    alignItems: "center",
    gap: 4,
    minWidth: 56,
  },
  navIconImage: {
    width: 32,
    height: 32,
  },
  navLabel: {
    color: "#145FA0",
    fontSize: 12,
    fontWeight: "600",
  },
  navCenterPressable: {
    alignItems: "center",
    marginTop: -52,
    zIndex: 2,
  },
  navCenterGroup: {
    height: 94,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  navCenterHalo: {
    position: "absolute",
    top: 6,
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: "#638F6A",
    opacity: 0.65,
  },
  navCenterButton: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: "#085491",
    alignItems: "center",
    justifyContent: "center",
  },
  navCenterLabel: {
    color: "#145FA0",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
  },
  searchIconWrap: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  searchIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 3,
    borderColor: "#FFFFFF",
  },
  searchIconHandle: {
    position: "absolute",
    width: 12,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#FFFFFF",
    transform: [{ rotate: "45deg" }],
    right: 4,
    bottom: 7,
  },
  profileShortcutRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  profileShortcutLink: {
    color: "#145FA0",
    fontSize: 16,
    fontWeight: "700",
  },
  carousel: {
    height: 96,
  },
  carouselWrap: {
    height: 96,
    marginBottom: 10,
  },
  carouselContent: {
    paddingRight: 8,
    gap: 10,
  },
  recipeCard: {
    width: 150,
    height: 96,
    borderRadius: 16,
    overflow: "hidden",
  },
  recipeCardImage: {
    width: 150,
    height: 96,
  },
  recipeCardImagePlaceholder: {
    backgroundColor: "#C8D8E2",
  },
  recipeCardContent: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  recipeCardTitle: {
    color: "#FFFFFF",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
  },
  recipeCardMeta: {
    color: "#E5E7EB",
    fontSize: 9,
    marginTop: 2,
  },
  carouselEmpty: {
    color: "#6B7280",
    fontSize: 14,
    paddingVertical: 20,
  },
  gameCard: {
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    height: 168,
    overflow: "hidden",
    flexDirection: "row",
  },
  gameCardLeft: {
    flex: 1,
    backgroundColor: "#145FA0",
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 18,
    paddingLeft: 14,
    paddingTop: 14,
    paddingBottom: 14,
    paddingRight: 10,
    justifyContent: "space-between",
  },
  gameCardTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    lineHeight: 20,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  gameCardSubtitle: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
  },
  gameTitleBox: {
    marginBottom: 4,
  },
  gameSubtitleBox: {
    marginBottom: 2,
  },
  gameCardRight: {
    width: 112,
    flexDirection: "row",
    alignItems: "stretch",
  },
  gamePlateWrap: {
    width: 44,
    height: "100%",
    backgroundColor: "#145FA0",
    overflow: "hidden",
  },
  gamePlateImage: {
    width: "100%",
    height: "100%",
  },
  gameFoodsWrap: {
    width: 68,
    height: "100%",
  },
  gameFoodsImage: {
    width: "100%",
    height: "100%",
  },
  gameButtonWrap: {
    backgroundColor: "#01AB51",
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    width: 200,
  },
  gameButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  statePill: {
    marginTop: 18,
    alignSelf: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#D7E3EB",
  },
  statePillLabel: {
    color: "#6B7280",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  statePillValue: {
    color: "#145FA0",
    fontSize: 16,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 2,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  scrollBody: {
    flex: 1,
  },
  creditsButton: {
    alignSelf: "center",
    marginTop: "auto",
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#D7E3EB",
  },
  creditsButtonText: {
    color: "#6B7280",
    fontSize: 13,
    fontWeight: "600",
  },
});