import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F7F8FA",
  },
  content: {
    flex: 1,
    paddingTop: 48,
    paddingHorizontal: 24,
    paddingBottom: 110,
  },
  logoRow: {
    position: "relative",
    marginHorizontal: -24,
    marginBottom: 22,
    paddingHorizontal: 24,
    paddingTop: 14,
    paddingBottom: 20,
    minHeight: 82,
    backgroundColor: "#F7F8FA",
  },
  logoRowBottomShadow: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 1,
    backgroundColor: "rgba(0,0,0,0.06)",
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 4,
  },
  logoImage: {
    width: 126,
    height: 42,
  },
  sectionTitle: {
    color: "#1C1C1C",
    fontSize: 26,
    lineHeight: 30,
    fontWeight: "800",
    marginBottom: 12,
  },
  profileCard: {
    backgroundColor: "#135E9A",
    borderRadius: 18,
    padding: 18,
    minHeight: 150,
    overflow: "hidden",
    marginBottom: 28,
  },
  profileCardTextWrap: {
    width: "66%",
  },
  profileCardTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "900",
    marginBottom: 8,
  },
  profileCardText: {
    color: "#EAF4FF",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    marginBottom: 14,
  },
  profileButton: {
    alignSelf: "flex-start",
    backgroundColor: "#55C06B",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  profileButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  profileIllustration: {
    position: "absolute",
    right: 10,
    bottom: 8,
    width: 108,
    height: 108,
    borderRadius: 54,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sectionHeaderTitle: {
    color: "#1C1C1C",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
  },
  sectionHeaderAction: {
    color: "#1C1C1C",
    fontSize: 16,
    fontWeight: "600",
  },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
    paddingTop: 12,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderTopColor: "#E6E6E6",
  },
  bottomNavRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-around",
    paddingHorizontal: 12,
  },
  navItem: {
    alignItems: "center",
    gap: 4,
    minWidth: 56,
  },
  navIconImage: {
    width: 32,
    height: 32,
  },
  navLabel: {
    color: "#145FA0",
    fontSize: 12,
    fontWeight: "600",
  },
  navCenterPressable: {
    alignItems: "center",
    marginTop: -52,
    zIndex: 2,
  },
  navCenterGroup: {
    height: 94,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  navCenterHalo: {
    position: "absolute",
    top: 6,
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: "#638F6A",
    opacity: 0.65,
  },
  navCenterButton: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: "#085491",
    alignItems: "center",
    justifyContent: "center",
  },
  navCenterLabel: {
    color: "#145FA0",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
  },
  searchIconWrap: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  searchIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 3,
    borderColor: "#FFFFFF",
  },
  searchIconHandle: {
    position: "absolute",
    width: 12,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#FFFFFF",
    transform: [{ rotate: "45deg" }],
    right: 4,
    bottom: 7,
  },
  profileShortcutRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  profileShortcutLink: {
    color: "#145FA0",
    fontSize: 16,
    fontWeight: "700",
  },
  suggestionGrid: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 26,
  },
  suggestionCard: {
    flex: 1,
    borderRadius: 16,
    overflow: "hidden",
    minHeight: 156,
    backgroundColor: "#0B7F4C",
  },
  suggestionCardAlt: {
    backgroundColor: "#D9E2E8",
  },
  suggestionCardSecondary: {
    backgroundColor: "#D9E2E8",
  },
  suggestionTop: {
    flex: 1,
    padding: 14,
    justifyContent: "flex-end",
  },
  suggestionLabel: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
  },
  suggestionLabelDark: {
    color: "#1C1C1C",
  },
  suggestionMeta: {
    color: "#F2F2F2",
    fontSize: 12,
    marginTop: 4,
  },
  gameCard: {
    borderRadius: 18,
    backgroundColor: "#145FA0",
    padding: 18,
    minHeight: 168,
    overflow: "hidden",
    flexDirection: "row",
  },
  gameCardContent: {
    flex: 1,
    paddingRight: 10,
  },
  gameCardTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "900",
    marginBottom: 6,
  },
  gameCardSubtitle: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "700",
    marginBottom: 16,
  },
  gameButton: {
    alignSelf: "flex-start",
    backgroundColor: "#55C06B",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  gameButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
  },
  plateCircle: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: "rgba(255,255,255,0.92)",
    alignSelf: "center",
    marginTop: 16,
  },
  statePill: {
    marginTop: 18,
    alignSelf: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#D7E3EB",
  },
  statePillLabel: {
    color: "#6B7280",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  statePillValue: {
    color: "#145FA0",
    fontSize: 16,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 2,
  },
});