import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 0,
    paddingBottom: 18,
  },
  scrollContent: {
    paddingBottom: 28,
  },
  primaryAction: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 18,
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
    shadowColor: "#196926",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 5,
  },
  primaryActionText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    color: "#1C1C1C",
    fontSize: 19,
    lineHeight: 24,
    fontWeight: "800",
    marginBottom: 4,
  },
  daySection: {
    marginBottom: 18,
  },
  dayLabel: {
    color: "#0E69B3",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "800",
    marginBottom: 6,
  },
  typeSection: {
    marginBottom: 12,
  },
  typeSectionTitle: {
    color: "#5E5E5E",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
    marginBottom: 8,
  },
  recordSection: {
    marginBottom: 10,
  },
  foodList: {
    borderTopWidth: 1,
    borderTopColor: "#E7E7E7",
  },
  foodRow: {
    paddingTop: 12,
    paddingBottom: 12,
  },
  foodRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: "#E7E7E7",
  },
  foodRowTop: {
    flexDirection: "row",
    alignItems: "center",
  },
  foodTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  foodRowTitle: {
    color: "#2A2A2A",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
  },
  foodHeartAmount: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  foodRowMeta: {
    color: "#A4A4A4",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    marginTop: 3,
  },
  emptyState: {
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    padding: 22,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#123B66",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  emptyStateTitle: {
    color: "#1C1C1C",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    textAlign: "center",
  },
  emptyStateText: {
    color: "#6B7280",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    textAlign: "center",
    marginTop: 6,
  },
  emptyStateButton: {
    marginTop: 16,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
    shadowColor: "#196926",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 5,
  },
  emptyStateButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
});
