import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  content: {
    flex: 1,
    paddingHorizontal: 22,
    paddingTop: 0,
    paddingBottom: 18,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  mainContent: {
    flexGrow: 1,
  },
  pageTitle: {
    color: "#1F1F1F",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
    marginTop: 8,
    marginBottom: 12,
  },
  fieldGroup: {
    marginBottom: 18,
  },
  fieldLabel: {
    color: "#1F1F1F",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
    marginBottom: 6,
  },
  dropdownButton: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#01AB51",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dropdownText: {
    flex: 1,
    color: "#01AB51",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
    marginRight: 8,
  },
  dropdownPlaceholder: {
    color: "#01AB51",
  },
  dropdownMenu: {
    marginTop: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#01AB51",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  dropdownOption: {
    minHeight: 42,
    paddingHorizontal: 12,
    justifyContent: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E6E6E6",
  },
  dropdownOptionActive: {
    backgroundColor: "#EAF8EF",
  },
  dropdownOptionText: {
    color: "#1F1F1F",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
  },
  dropdownOptionTextActive: {
    color: "#01AB51",
    fontFamily: "Poppins-Bold",
  },
  addFoodButton: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#196926",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  addFoodButtonText: {
    color: "#196926",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  sectionLabel: {
    color: "#1F1F1F",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
    marginBottom: 8,
  },
  addedFoodsSection: {
    gap: 12,
    minHeight: 220,
  },
  spacer: {
    flexGrow: 1,
    minHeight: 24,
  },
  loadingWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  heroCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    padding: 22,
    marginBottom: 18,
    shadowColor: "#123B66",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 3,
  },
  heroBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#EAF4FF",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 14,
  },
  heroBadgeText: {
    color: "#145FA0",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  heroTitle: {
    color: "#1C1C1C",
    fontSize: 26,
    lineHeight: 31,
    fontWeight: "900",
    marginBottom: 10,
  },
  heroText: {
    color: "#5F5F5F",
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "500",
  },
  sectionHeader: {
    marginBottom: 12,
  },
  sectionTitle: {
    color: "#1C1C1C",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    marginBottom: 4,
  },
  sectionSubtitle: {
    color: "#6B7280",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  mealTypeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 18,
  },
  mealTypeChip: {
    minHeight: 40,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D4DCE6",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  mealTypeChipActive: {
    backgroundColor: "#145FA0",
    borderColor: "#145FA0",
  },
  mealTypeChipText: {
    color: "#1C1C1C",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
  mealTypeChipTextActive: {
    color: "#FFFFFF",
  },
  searchBarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
  },
  searchInputWrap: {
    flex: 1,
    minHeight: 46,
    borderRadius: 23,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D4DCE6",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
  },
  searchInputIconWrap: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: "#145FA0",
    fontSize: 14,
    fontWeight: "500",
    paddingVertical: 0,
  },
  searchButton: {
    minHeight: 46,
    paddingHorizontal: 16,
    borderRadius: 23,
    backgroundColor: "#145FA0",
    alignItems: "center",
    justifyContent: "center",
  },
  searchButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "800",
  },
  resultList: {
    gap: 10,
    marginBottom: 18,
  },
  resultCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: "#123B66",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  resultThumbWrap: {
    width: 60,
    height: 60,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#EAF2F8",
  },
  resultThumb: {
    width: "100%",
    height: "100%",
  },
  resultContent: {
    flex: 1,
  },
  resultTitle: {
    color: "#1C1C1C",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
  },
  resultMeta: {
    color: "#6B7280",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    marginTop: 3,
  },
  resultHeart: {
    color: "#145FA0",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    marginTop: 6,
  },
  resultAction: {
    minHeight: 38,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: "#01AB51",
    alignItems: "center",
    justifyContent: "center",
  },
  resultActionDisabled: {
    backgroundColor: "#D4DCE6",
  },
  resultActionText: {
    color: "#FFFFFF",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  selectedSection: {
    marginBottom: 18,
  },
  selectedCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#123B66",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  selectedCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  selectedTitleWrap: {
    flex: 1,
  },
  selectedFoodTitle: {
    color: "#1C1C1C",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
  },
  selectedFoodMeta: {
    color: "#6B7280",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    marginTop: 3,
  },
  selectedFoodHeart: {
    color: "#01AB51",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "800",
    textAlign: "right",
  },
  heartOptionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  heartOptionChip: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D4DCE6",
    backgroundColor: "#F7F8FA",
    alignItems: "center",
    justifyContent: "center",
  },
  heartOptionChipActive: {
    backgroundColor: "#145FA0",
    borderColor: "#145FA0",
  },
  heartOptionText: {
    color: "#1C1C1C",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  heartOptionTextActive: {
    color: "#FFFFFF",
  },
  removeButton: {
    alignSelf: "flex-start",
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#FDECEC",
  },
  removeButtonText: {
    color: "#B42318",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  footerCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 18,
    marginBottom: 18,
    shadowColor: "#123B66",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  footerText: {
    color: "#6B7280",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  saveButton: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    shadowColor: "#196926",
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 0,
    elevation: 2,
    marginTop: 8,
  },
  saveButtonDisabled: {
    backgroundColor: "#8FCB99",
  },
  saveButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  foodPickerScreen: {
    flex: 1,
  },
  foodPickerHeader: {
    minHeight: 72,
    paddingHorizontal: 22,
    paddingTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  foodPickerCloseButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  foodPickerTitle: {
    color: "#1F1F1F",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  foodPickerHeaderSpacer: {
    width: 40,
    height: 40,
  },
  foodPickerContent: {
    paddingHorizontal: 22,
    paddingBottom: 28,
  },
  statusText: {
    color: "#145FA0",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    marginBottom: 10,
  },
  errorText: {
    color: "#B42318",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    marginBottom: 10,
  },
  emptyState: {
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    padding: 22,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#123B66",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  emptyStateTitle: {
    color: "#1C1C1C",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    textAlign: "center",
  },
  emptyStateText: {
    color: "#6B7280",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    textAlign: "center",
    marginTop: 6,
  },
});
