import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 0,
    paddingBottom: 18,
  },
  scrollContent: {
    paddingBottom: 28,
  },
  primaryAction: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#49B65D",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 18,
    shadowColor: "#1D6F2F",
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 4,
  },
  primaryActionText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "800",
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    color: "#1C1C1C",
    fontSize: 19,
    lineHeight: 24,
    fontWeight: "800",
    marginBottom: 4,
  },
  daySection: {
    marginBottom: 18,
  },
  dayLabel: {
    color: "#0E69B3",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "800",
    marginBottom: 6,
  },
  typeSection: {
    marginBottom: 12,
  },
  typeSectionTitle: {
    color: "#5E5E5E",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
    marginBottom: 8,
  },
  recordSection: {
    marginBottom: 10,
  },
  recordMealLabel: {
    color: "#5E5E5E",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
    marginBottom: 8,
  },
  foodList: {
    borderTopWidth: 1,
    borderTopColor: "#E7E7E7",
  },
  foodRow: {
    paddingTop: 12,
    paddingBottom: 12,
  },
  foodRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: "#E7E7E7",
  },
  foodRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  foodRowTitle: {
    flex: 1,
    color: "#2A2A2A",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
  },
  foodHeartIcon: {
    marginLeft: 6,
  },
  foodRowMeta: {
    color: "#A4A4A4",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    marginTop: 3,
  },
  emptyState: {
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    padding: 22,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#123B66",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  emptyStateTitle: {
    color: "#1C1C1C",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    textAlign: "center",
  },
  emptyStateText: {
    color: "#6B7280",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    textAlign: "center",
    marginTop: 6,
  },
  emptyStateButton: {
    marginTop: 16,
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: "#01AB51",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  emptyStateButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
  },
});
