import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  content: {
    flex: 1,
    paddingHorizontal: 22,
    paddingTop: 0,
    paddingBottom: 18,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  mainContent: {
    flexGrow: 1,
  },
  pageTitle: {
    color: "#1F1F1F",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
    marginTop: 8,
    marginBottom: 12,
  },
  fieldGroup: {
    marginBottom: 18,
  },
  fieldLabel: {
    color: "#1F1F1F",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
    marginBottom: 6,
  },
  dropdownButton: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#01AB51",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dropdownText: {
    flex: 1,
    color: "#01AB51",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
    marginRight: 8,
  },
  dropdownPlaceholder: {
    color: "#01AB51",
  },
  dropdownMenu: {
    marginTop: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#01AB51",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  dropdownOption: {
    minHeight: 42,
    paddingHorizontal: 12,
    justifyContent: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E6E6E6",
  },
  dropdownOptionActive: {
    backgroundColor: "#EAF8EF",
  },
  dropdownOptionText: {
    color: "#1F1F1F",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
  },
  dropdownOptionTextActive: {
    color: "#01AB51",
    fontFamily: "Poppins-Bold",
  },
  addFoodButton: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
    shadowColor: "#196926",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 5,
  },
  addFoodButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  sectionLabel: {
    color: "#1F1F1F",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
    marginBottom: 8,
  },
  addedFoodsSection: {
    minHeight: 220,
  },
  spacer: {
    flexGrow: 1,
    minHeight: 24,
  },
  loadingWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  cameraButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#085491",
    alignItems: "center",
    justifyContent: "center",
  },
  foodDetailCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E7E7E7",
    padding: 16,
    marginTop: 8,
    marginBottom: 16,
  },
  foodDetailTitle: {
    color: "#1C1C1C",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    marginBottom: 4,
  },
  foodDetailMeta: {
    color: "#6B7280",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    marginBottom: 12,
  },
  portionFieldGroup: {
    marginBottom: 14,
  },
  portionFieldLabel: {
    color: "#1F1F1F",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
    marginBottom: 6,
  },
  portionMenu: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#01AB51",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  portionOption: {
    minHeight: 40,
    paddingHorizontal: 12,
    justifyContent: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E6E6E6",
  },
  portionOptionActive: {
    backgroundColor: "#EAF8EF",
  },
  portionOptionText: {
    color: "#1F1F1F",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
  },
  portionOptionTextActive: {
    color: "#01AB51",
    fontFamily: "Poppins-Bold",
  },
  heroCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    padding: 22,
    marginBottom: 18,
    shadowColor: "#123B66",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 3,
  },
  heroBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#EAF4FF",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 14,
  },
  heroBadgeText: {
    color: "#145FA0",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  heroTitle: {
    color: "#1C1C1C",
    fontSize: 26,
    lineHeight: 31,
    fontWeight: "900",
    marginBottom: 10,
  },
  heroText: {
    color: "#5F5F5F",
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "500",
  },
  sectionHeader: {
    marginBottom: 12,
  },
  sectionTitle: {
    color: "#1C1C1C",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    marginBottom: 4,
  },
  sectionSubtitle: {
    color: "#6B7280",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  sectionSubtitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  heartAmountRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  mealTypeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 18,
  },
  mealTypeChip: {
    minHeight: 40,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D4DCE6",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  mealTypeChipActive: {
    backgroundColor: "#145FA0",
    borderColor: "#145FA0",
  },
  mealTypeChipText: {
    color: "#1C1C1C",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
  mealTypeChipTextActive: {
    color: "#FFFFFF",
  },
  searchBarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
  },
  searchInputWrap: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#B7CBE1",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 14,
    paddingRight: 16,
  },
  searchInputIconWrap: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: "#145FA0",
    fontSize: 14,
    fontWeight: "500",
    paddingVertical: 0,
  },
  foodPickerLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  foodPickerScreen: {
    flex: 1,
  },
  foodPickerHeaderSpacer: {
    height: 92,
  },
  foodPickerContent: {
    flex: 1,
    paddingHorizontal: 22,
    paddingBottom: 28,
    paddingTop: 16,
  },
  popupResultsCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 14,
    shadowColor: "#123B66",
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 3,
    marginBottom: 14,
  },
  popupResultsTitle: {
    color: "#1C1C1C",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 14,
  },
  popupResultsStatus: {
    color: "#1C1C1C",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    textAlign: "center",
    marginBottom: 14,
  },
  popupResultsError: {
    color: "#B42318",
  },
  popupEmptyState: {
    flex: 1,
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
  },
  popupEmptyStateText: {
    color: "#1C1C1C",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    textAlign: "center",
  },
  popupResultsList: {
    flex: 1,
  },
  popupResultRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E9E9E9",
  },
  popupResultMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingTop: 2,
  },
  popupResultCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 3,
    borderWidth: 1.5,
    borderColor: "#01AB51",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  popupResultCheckboxActive: {
    backgroundColor: "#01AB51",
  },
  popupResultTextWrap: {
    flex: 1,
  },
  popupResultTitle: {
    color: "#4BB05B",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
  },
  popupResultTitleActive: {
    color: "#4BB05B",
  },
  popupResultMeta: {
    color: "#A5A5A5",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    marginTop: 2,
  },
  popupResultActionWrap: {
    alignItems: "flex-end",
    minWidth: 120,
  },
  popupResultActionButton: {
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  popupPortionMenu: {
    width: 120,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E3E3E3",
    overflow: "hidden",
    shadowColor: "#123B66",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 3,
    marginTop: 4,
  },
  popupPortionOption: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  popupPortionOptionLast: {
    borderBottomWidth: 0,
  },
  popupPortionOptionActive: {
    backgroundColor: "#EAF8EF",
  },
  popupPortionText: {
    color: "#1F1F1F",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
  },
  popupPortionTextActive: {
    color: "#01AB51",
    fontWeight: "700",
  },
  searchButton: {
    minHeight: 46,
    paddingHorizontal: 16,
    borderRadius: 23,
    backgroundColor: "#145FA0",
    alignItems: "center",
    justifyContent: "center",
  },
  searchButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "800",
  },
  resultList: {
    gap: 10,
    marginBottom: 18,
  },
  resultCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: "#123B66",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  resultThumbWrap: {
    width: 60,
    height: 60,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#EAF2F8",
  },
  resultThumb: {
    width: "100%",
    height: "100%",
  },
  resultContent: {
    flex: 1,
  },
  resultTitle: {
    color: "#1C1C1C",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
  },
  resultMeta: {
    color: "#6B7280",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    marginTop: 3,
  },
  resultHeart: {
    color: "#145FA0",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    marginTop: 6,
  },
  resultAction: {
    minHeight: 38,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: "#01AB51",
    alignItems: "center",
    justifyContent: "center",
  },
  resultActionDisabled: {
    backgroundColor: "#D4DCE6",
  },
  resultActionText: {
    color: "#FFFFFF",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  selectedSection: {
    marginBottom: 18,
  },
  selectedCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#123B66",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  selectedCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  selectedTitleWrap: {
    flex: 1,
  },
  selectedFoodTitle: {
    color: "#1C1C1C",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
  },
  selectedFoodMeta: {
    color: "#6B7280",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    marginTop: 3,
  },
  selectedFoodHeart: {
    color: "#01AB51",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "800",
    textAlign: "right",
  },
  heartOptionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  heartOptionChip: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D4DCE6",
    backgroundColor: "#F7F8FA",
    alignItems: "center",
    justifyContent: "center",
  },
  heartOptionChipActive: {
    backgroundColor: "#145FA0",
    borderColor: "#145FA0",
  },
  heartOptionText: {
    color: "#1C1C1C",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  heartOptionTextActive: {
    color: "#FFFFFF",
  },
  removeButton: {
    alignSelf: "flex-start",
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#FDECEC",
  },
  removeButtonText: {
    color: "#B42318",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  selectedFoodRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  selectedFoodCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: "#D4DCE6",
  },
  selectedFoodInfo: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  selectedFoodName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1C1C1C",
  },
  selectedFoodMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
  },
  selectedFoodQuantityText: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "500",
  },
  selectedFoodRemoveBtn: {
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  selectedFoodRemoveText: {
    fontSize: 22,
    color: "#B42318",
    lineHeight: 22,
    fontWeight: "400",
  },
  footerCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 18,
    marginBottom: 18,
    shadowColor: "#123B66",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  footerText: {
    color: "#6B7280",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  saveButton: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
    shadowColor: "#196926",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 5,
    marginTop: 8,
  },
  saveButtonDisabled: {
    backgroundColor: "#8FCB99",
    borderBottomColor: "#5A9467",
  },
  saveButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  popupAddButton: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
    shadowColor: "#196926",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 5,
    marginTop: 16,
  },
  popupAddButtonDisabled: {
    backgroundColor: "#8FCB99",
    borderBottomColor: "#5A9467",
  },
  popupAddButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  statusText: {
    color: "#145FA0",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    marginBottom: 10,
  },
  errorText: {
    color: "#B42318",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    marginBottom: 10,
  },
  emptyState: {
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    padding: 22,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#123B66",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  emptyStateTitle: {
    color: "#1C1C1C",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    textAlign: "center",
  },
  emptyStateText: {
    color: "#6B7280",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    textAlign: "center",
    marginTop: 6,
  },
});
