import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 4,
    paddingBottom: 24,
  },
  sectionTitle: {
    color: "#1F1F1F",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    marginBottom: 10,
  },
  sectionSubtitle: {
    color: "#5F5F5F",
    fontSize: 16,
    lineHeight: 26,
    fontWeight: "500",
    marginBottom: 35,
  },
  resultCard: {
    backgroundColor: "rgba(113,113,113,0.12)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  resultTitle: {
    color: "#1F1F1F",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
    marginBottom: 8,
  },
  imcRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  imcColumn: {
    alignItems: "center",
    width: 100,
  },
  imcLabel: {
    color: "#1F1F1F",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "500",
    textAlign: "center",
    marginBottom: 10,
  },
  imcBubble: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: "#E2E2E2",
    alignItems: "center",
    justifyContent: "center",
  },
  imcValue: {
    color: "#1F1F1F",
    fontSize: 22,
    lineHeight: 22,
    fontWeight: "500",
  },
  resultTextWrap: {
    flex: 1,
    paddingTop: 2,
  },
  resultText: {
    color: "#5F5F5F",
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "500",
  },
  resultTextHighlight: {
    color: "#085491",
    fontWeight: "800",
  },
  metaTitle: {
    color: "#1F1F1F",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
    marginBottom: 10,
  },
  heartsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 12,
  },
  heartCard: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  heartIconWrap: {
    width: 72,
    height: 72,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  heartIconText: {
    position: "absolute",
    color: "#FFFFFF",
    fontSize: 22,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: "Poppins-Bold",
    textAlign: "center",
  },
  explanationText: {
    color: "#5F5F5F",
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "500",
    marginBottom: 14,
  },
  explanationHighlight: {
    color: "#085491",
    fontWeight: "800",
  },
  profileLinkButton: {
    alignSelf: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  profileLinkText: {
    color: "#085491",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    color: "#085491",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    marginTop: 10,
  },
});