import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 0,
    paddingBottom: 28,
  },
  title: {
    color: "#1F1F1F",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    marginBottom: 12,
  },
  subtitle: {
    color: "#5F5F5F",
    fontSize: 16,
    lineHeight: 26,
    fontWeight: "500",
    marginBottom: 18,
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    color: "#111111",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "700",
    marginBottom: 6,
    fontFamily: "Inter-SemiBold",
  },
  input: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#B2B2B2",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    color: "#1C1C1C",
    fontSize: 14,
    fontWeight: "400",
    fontFamily: "Inter-Regular",
  },
  actionButton: {
    alignSelf: "center",
    width: 196,
    minHeight: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 22,
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
    shadowColor: "#196926",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 5,
  },
  actionButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  errorText: {
    color: "#B42318",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 10,
  },
});