import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 22,
    paddingBottom: 18,
  },
   title: {
    color: "black",
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    marginBottom: 9,
  },
  heroCard: {
    backgroundColor: "#145FA0",
    borderRadius: 28,
    padding: 22,
    marginBottom: 18,
    overflow: "hidden",
    shadowColor: "#123B66",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 18,
    elevation: 6,
  },
  heroBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.16)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 14,
  },
  heroBadgeText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 26,
    lineHeight: 31,
    fontWeight: "900",
    marginBottom: 10,
  },
  heroText: {
    color: "#EAF4FF",
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "500",
    marginBottom: 18,
  },
  heroContentRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 16,
  },
  heroCopyWrap: {
    flex: 1,
    gap: 12,
  },
  heroMiniStat: {
    width: 74,
    height: 74,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  heroMiniStatValue: {
    color: "#FFFFFF",
    fontSize: 24,
    lineHeight: 24,
    fontWeight: "900",
  },
  heroMiniStatLabel: {
    color: "#EAF4FF",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "600",
    marginTop: 2,
  },
  heroHint: {
    color: "#EAF4FF",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
  },
  heroImage: {
    width: 122,
    height: 122,
    alignSelf: "flex-end",
  },
  setupCardImage: {
    width: 116,
    height: 132,
    borderRadius: 11
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    color: "#1C1C1C",
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
    marginBottom: 4,
  },
  sectionSubtitle: {
    color: "#6B7280",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
  },
  setupCard: {
    backgroundColor: "#085491",
    borderRadius: 24,
    padding: 18,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    shadowColor: "#123B66",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 3,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 62,
    paddingHorizontal: 16,
  },
  emptyStateTitle: {
    color: "#111111",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 10,
  },
  emptyStateText: {
    color: "#111111",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    textAlign: "center",
    maxWidth: 240,
  },
  setupCardIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: "#EAF4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  setupCardIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#01AB51",
  },
  setupCardTextWrap: {
    flex: 1,
  },
  setupCardTitle: {
    color: "white",
    fontSize: 22,
    lineHeight: 24,
    fontWeight: "800",
    marginBottom: 8,
  },
  setupCardText: {
    color: "white",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
    marginBottom: 0,
  },
  setupCardArrow: {
    color: "#01AB51",
    fontSize: 24,
    fontWeight: "800",
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    color: "#1C1C1C",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    marginBottom: 6,
  },
  input: {
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D4DCE6",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 14,
    color: "#1C1C1C",
    fontSize: 15,
    fontWeight: "500",
  },
  helperText: {
    color: "#6B7280",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 6,
  },
  actionButton: {
    alignSelf: "flex-start",
    backgroundColor: "#01AB51",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 10,
  },
  actionButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  errorText: {
    color: "#B42318",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
});
