import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    height: 120,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 32,
    paddingTop: 14,
    paddingBottom: 16,
    justifyContent: "flex-end",
    shadowColor: "#000000",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  headerStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusTime: {
    color: "#021433",
    fontSize: 16,
    lineHeight: 16,
    fontWeight: "500",
  },
  statusIcons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  statusSignal: {
    width: 18,
    height: 10,
    borderRadius: 2,
    backgroundColor: "#021433",
  },
  statusWifi: {
    width: 15,
    height: 11,
    borderRadius: 999,
    backgroundColor: "#021433",
  },
  statusBattery: {
    width: 27,
    height: 13,
    borderRadius: 3,
    backgroundColor: "#021433",
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: 16,
  },
  brandProfile: {
    color: "#01AB51",
    fontSize: 17,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  content: {
    flex: 1,
    paddingHorizontal: 32,
    paddingTop: 18,
    paddingBottom: 138,
  },
  sectionTitle: {
    color: "#1C1C1C",
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
    marginBottom: 20,
  },
  profileCard: {
    borderRadius: 12,
    backgroundColor: "#085491",
    paddingHorizontal: 19,
    paddingTop: 13,
    paddingBottom: 20,
    marginBottom: 20,
  },
  profileCardTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    marginBottom: 4,
  },
  profileCardMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  profileCardMetaLabel: {
    color: "#B2B2B2",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "700",
  },
  profileCardMetaValue: {
    color: "#B2B2B2",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "500",
  },
  goalHeading: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
    marginTop: 10,
  },
  goalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 12,
  },
  goalBadge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#F5F5F5",
    alignItems: "center",
    justifyContent: "center",
  },
  goalBadgeValue: {
    fontSize: 22,
    lineHeight: 22,
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
  },
  sectionBlock: {
    marginBottom: 16,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  sectionBlockTitle: {
    color: "#1F1F1F",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
  },
  sectionAction: {
    color: "#1F1F1F",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
  },
  actionButton: {
    height: 44,
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
    shadowColor: "#196926",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 5,
  },
  actionButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  analyticsBlock: {
    marginTop: 4,
  },
  analyticsSubtitle: {
    color: "#1F1F1F",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
    marginBottom: 16,
  },
  analyticsPlaceholder: {
    height: 170,
    borderRadius: 18,
    backgroundColor: "#F7F8FA",
    alignItems: "center",
    justifyContent: "center",
  },
  analyticsPlaceholderText: {
    color: "#085491",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    color: "#145FA0",
    fontSize: 14,
    fontWeight: "600",
    marginTop: 10,
  },
  bottomSpacer: {
    height: 14,
  },
  profileCardRow: {
    flex: 1,
    minHeight: 0,
  },
});
