import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  content: {
    flex: 1,
    paddingTop: 48,
    paddingHorizontal: 24,
    paddingBottom: 110,
  },
  logoRow: {
    position: "relative",
    marginHorizontal: -24,
    paddingHorizontal: 24,
    paddingTop: 14,
    paddingBottom: 20,
    minHeight: 82,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 18,
  },
  searchInputWrap: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#B7CBE1",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 14,
    paddingRight: 16,
  },
  searchInputIconWrap: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: "#145FA0",
    fontSize: 14,
    fontWeight: "500",
    paddingVertical: 0,
  },
  searchBarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 18,
  },
  cameraButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#085491",
    alignItems: "center",
    justifyContent: "center",
  },
  cameraIcon: {
    width: 22,
    height: 16,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  cameraIconLens: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  cameraIconTop: {
    position: "absolute",
    top: -4,
    width: 10,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#FFFFFF",
  },
  resultsTitle: {
    color: "#1C1C1C",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    marginBottom: 14,
  },
  resultsList: {
    flexGrow: 1,
    paddingBottom: 12,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingTop: 36,
  },
  emptyStateTitle: {
    color: "#1C1C1C",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    textAlign: "center",
  },
  emptyStateText: {
    color: "#1C1C1C",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    textAlign: "center",
    marginTop: 6,
  },
  redWarningState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 24,
  },
  redWarningIcon: {
    marginBottom: 16,
  },
  redWarningTitle: {
    color: "#1C1C1C",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
    textAlign: "center",
  },
  redWarningSubtitle: {
    color: "#1C1C1C",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 10,
  },
  redWarningText: {
    color: "#1C1C1C",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    textAlign: "center",
    marginTop: 10,
    maxWidth: 280,
  },
  redWarningLink: {
    color: "#0F5F9A",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    textAlign: "center",
    textDecorationLine: "underline",
    marginTop: 18,
  },
  resultCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#E8E8E8",
  },
  resultThumbWrap: {
    width: 62,
    height: 62,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#E7EEF7",
    marginRight: 14,
  },
  resultThumb: {
    width: "100%",
    height: "100%",
  },
  resultContent: {
    flex: 1,
    paddingRight: 10,
  },
  resultName: {
    color: "#3A3A3A",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
  },
  resultHeart: {
    marginTop: 6,
    fontSize: 19,
    lineHeight: 20,
    fontWeight: "700",
  },
  resultStatusText: {
    color: "#145FA0",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    marginBottom: 10,
  },
  resultErrorText: {
    color: "#B42318",
  },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
    paddingTop: 12,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderTopColor: "#E6E6E6",
  },
  bottomNavRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-around",
    paddingHorizontal: 12,
  },
  navItem: {
    alignItems: "center",
    gap: 4,
    minWidth: 56,
  },
  navIconImage: {
    width: 32,
    height: 32,
  },
  navLabel: {
    color: "#145FA0",
    fontSize: 12,
    fontWeight: "600",
  },
  navCenterPressable: {
    alignItems: "center",
    marginTop: -52,
    zIndex: 2,
  },
  navCenterGroup: {
    height: 94,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  navCenterHalo: {
    position: "absolute",
    top: 6,
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: "#638F6A",
    opacity: 0.65,
  },
  navCenterButton: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: "#085491",
    alignItems: "center",
    justifyContent: "center",
  },
  navCenterLabel: {
    color: "#145FA0",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
  },
  searchIconWrap: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  searchIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 3,
    borderColor: "#FFFFFF",
  },
  searchIconHandle: {
    position: "absolute",
    width: 12,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#FFFFFF",
    transform: [{ rotate: "45deg" }],
    right: 4,
    bottom: 7,
  },
});