import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  scrollContent: {
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 40,
  },
  addButton: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 24,
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
    shadowColor: "#196926",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 5,
  },
  addButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1C1C1C",
    marginBottom: 14,
    marginTop: 4,
  },
  groupSection: {
    marginBottom: 14,
  },
  groupLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1C1C1C",
    marginBottom: 6,
  },
  groupDropdownButton: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1.5,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
  },
  groupDropdownText: {
    fontSize: 14,
    fontWeight: "500",
  },
  groupDropdownMenu: {
    borderWidth: 1.5,
    borderTopWidth: 0,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    maxHeight: 200,
  },
  groupDropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  groupDropdownItemText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#1C1C1C",
  },
  addedSectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1C1C1C",
    marginBottom: 10,
    marginTop: 8,
  },
  foodRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  foodRowCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 3,
    borderWidth: 1.5,
    borderColor: "#D4DCE6",
    flexShrink: 0,
  },
  foodRowName: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
  },
  foodRowRemoveBtn: {
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  foodRowRemoveText: {
    fontSize: 20,
    color: "#B42318",
    lineHeight: 22,
    fontWeight: "400",
  },
  exportFloatingButton: {
    position: "absolute",
    left: 22,
    right: 22,
    bottom: 24,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
    shadowColor: "#196926",
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 10,
    zIndex: 50,
  },
  exportButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
});

export const popupStyles = StyleSheet.create({
  foodPickerLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
  },
  foodPickerHeaderSpacer: {
    height: 92,
  },
  foodPickerScreen: {
    flex: 1,
  },
  foodPickerContent: {
    flex: 1,
    paddingHorizontal: 22,
    paddingBottom: 28,
    paddingTop: 16,
  },
  searchBarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
  },
  searchInputWrap: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#B7CBE1",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 14,
    paddingRight: 16,
  },
  searchInputIconWrap: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: "#145FA0",
    fontSize: 14,
    fontWeight: "500",
    paddingVertical: 0,
  },
  cameraButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#085491",
    alignItems: "center",
    justifyContent: "center",
  },
  popupResultsCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 14,
    shadowColor: "#123B66",
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 3,
    marginBottom: 14,
  },
  popupResultsTitle: {
    color: "#1C1C1C",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 14,
  },
  popupResultsStatus: {
    color: "#1C1C1C",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    textAlign: "center",
    marginBottom: 14,
  },
  popupResultsError: {
    color: "#B42318",
  },
  popupEmptyState: {
    flex: 1,
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
  },
  popupEmptyStateText: {
    color: "#1C1C1C",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    textAlign: "center",
  },
  popupResultsList: {
    flex: 1,
  },
  popupResultRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E9E9E9",
  },
  popupResultMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingTop: 2,
  },
  popupResultCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 3,
    borderWidth: 1.5,
    borderColor: "#01AB51",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  popupResultCheckboxActive: {
    backgroundColor: "#01AB51",
  },
  popupResultTitle: {
    color: "#4BB05B",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
  },
  popupResultTitleActive: {
    color: "#4BB05B",
  },
  popupResultActionWrap: {
    alignItems: "flex-end",
    minWidth: 120,
  },
  popupResultActionButton: {
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  popupPortionMenu: {
    width: 120,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E3E3E3",
    overflow: "hidden",
    shadowColor: "#123B66",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 3,
    marginTop: 4,
  },
  popupPortionOption: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  popupPortionOptionLast: {
    borderBottomWidth: 0,
  },
  popupPortionOptionActive: {
    backgroundColor: "#EAF8EF",
  },
  popupPortionText: {
    color: "#1F1F1F",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
  },
  popupPortionTextActive: {
    color: "#01AB51",
    fontWeight: "700",
  },
  popupAddButton: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#4BB05B",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    borderBottomWidth: 3,
    borderBottomColor: "#196926",
    shadowColor: "#196926",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 5,
    marginTop: 16,
  },
  popupAddButtonDisabled: {
    backgroundColor: "#8FCB99",
    borderBottomColor: "#5A9467",
  },
  popupAddButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
  },
});
