import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#414141",
    overflow: "hidden",
  },
  player: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000000",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(65, 65, 65, 0.24)",
  },
  titleCard: {
    position: "absolute",
    top: 100,
    left: 0,
    width: 313,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopRightRadius: 20,
    shadowColor: "#01AB51",
    shadowOffset: { width: 2, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  title: {
    color: "#01AB51",
    fontSize: 32,
    fontWeight: "700",
    lineHeight: 36,
  },
  foodSectionTitle: {
    position: "absolute",
    top: 156,
    left: 32,
    color: "#1F1F1F",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    zIndex: 11,
  },
  foodRail: {
    position: "absolute",
    top: 177,
    height: 85,
    paddingTop: 13,
    paddingBottom: 13,
    paddingLeft: 13.5,
    backgroundColor: "#DADADA",
    borderRadius: 62,
    shadowColor: "#000000",
    shadowOpacity: 0,
    elevation: 0,
    zIndex: 10,
  },
  foodRailContent: {
    alignItems: "center",
    paddingRight: 24,
    paddingTop: 0,
  },
  foodRailCard: {
    width: 68,
    marginRight: 14,
    alignItems: "center",
  },
  foodRailThumbWrap: {
    width: 53,
    height: 53,
    borderRadius: 26.5,
    backgroundColor: "#FFFFFF",
    borderWidth: 0.855,
    borderColor: "rgba(31,31,31,0.16)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  foodRailThumb: {
    width: 53,
    height: 53,
    borderRadius: 26.5,
  },
  foodRailLabel: {
    color: "#1F1F1F",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 4,
    transform: [{ translateY: 1 }],
  },
  foodRailGroup: {
    color: "#6A6A6A",
    fontSize: 8,
    lineHeight: 10,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 4,
  },
  skipButton: {
    position: "absolute",
    right: 16,
    bottom: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  skipText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  skipArrow: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 20,
  },
});